import MarketplaceShell from "@/components/MarketplaceShell";
import { trpc } from "@/lib/trpc";
import { formatNaira } from "@shared/marketplace";
import { CheckCircle2, RotateCcw, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

export default function AdminWalletOrders() {
  const utils = trpc.useUtils();
  const deliveries = trpc.marketplace.admin.ordersAwaitingDelivery.useQuery();
  const returnWindow = trpc.marketplace.admin.ordersInRewardReturnWindow.useQuery();
  const policy = trpc.marketplace.admin.referralRewardSettings.useQuery();
  const [minimumSpend, setMinimumSpend] = useState("");
  const [bonusAmount, setBonusAmount] = useState("");
  const [postSaleReference, setPostSaleReference] = useState("");
  const [postSaleType, setPostSaleType] = useState<"cashback" | "review">("cashback");
  const [postSaleAmount, setPostSaleAmount] = useState("");
  const refresh = async () => { await Promise.all([utils.marketplace.admin.ordersAwaitingDelivery.invalidate(), utils.marketplace.admin.ordersInRewardReturnWindow.invalidate(), utils.marketplace.admin.referralRewardSettings.invalidate()]); };
  const releaseWallet = trpc.marketplace.admin.markWalletOrderDelivered.useMutation({ onSuccess: async () => { await refresh(); toast.success("Delivery marked. The buyer can now confirm receipt before vendor escrow is released."); } });
  const markDelivery = trpc.marketplace.admin.markOrderDelivered.useMutation({ onSuccess: async data => { await refresh(); toast.success(data.bonusReward.queued ? "Delivery confirmed. Referral bonuses are pending for 48 hours." : "Delivery confirmed."); } });
  const markReturned = trpc.marketplace.admin.markOrderReturned.useMutation({ onSuccess: async data => { await refresh(); toast.success(`${data.cancelledRewards} pending reward(s) cancelled for the returned order.`); } });
  const savePolicy = trpc.marketplace.admin.saveReferralRewardSettings.useMutation({ onSuccess: async () => { setMinimumSpend(""); setBonusAmount(""); await refresh(); toast.success("Referral reward policy saved for new referral links."); } });
  const createPostSaleBonus = trpc.marketplace.admin.createPostSaleBonus.useMutation({ onSuccess: async data => { setPostSaleReference(""); setPostSaleAmount(""); await refresh(); toast.success(`${data.type === "cashback" ? "Cashback" : "Verified review"} bonus is pending until ${new Date(data.releaseAt).toLocaleString()}.`); } });
  const submitPolicy = (event: FormEvent) => {
    event.preventDefault();
    const minimumFirstOrderSubtotal = Number(minimumSpend || policy.data?.minimumFirstOrderSubtotal);
    const referralBonusAmount = Number(bonusAmount || policy.data?.referralBonusAmount);
    if (!Number.isSafeInteger(minimumFirstOrderSubtotal) || !Number.isSafeInteger(referralBonusAmount)) return toast.error("Enter whole-Naira policy values.");
    savePolicy.mutate({ minimumFirstOrderSubtotal, referralBonusAmount });
  };
  const submitPostSaleBonus = (event: FormEvent) => {
    event.preventDefault();
    const amount = Number(postSaleAmount);
    if (!postSaleReference.trim() || !Number.isSafeInteger(amount) || amount < 50) return toast.error("Enter a delivered order reference and a whole-Naira amount of at least ₦50.");
    createPostSaleBonus.mutate({ reference: postSaleReference.trim().toUpperCase(), type: postSaleType, amount });
  };

  return <MarketplaceShell><div className="page-shell pb-12"><section style={{ marginTop: 32 }}><span className="eyebrow">Administrator</span><h1 className="page-title">Delivery, escrow and rewards.</h1><p className="section-kicker">Mark delivery only after the buyer receives the order. For local-vendor wallet orders, the buyer must confirm receipt before vendor escrow is released; eligible Shopping Bonus remains pending for the 48-hour return window.</p></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-slate-800"><SlidersHorizontal size={19} /><h2 className="text-base font-extrabold">Referral reward policy</h2></div><p className="mt-1 text-sm leading-6 text-slate-600">These values apply to referral links created after the change. Existing links retain their saved eligibility threshold and reward amount.</p><form className="mt-4 grid gap-3 md:grid-cols-3" onSubmit={submitPolicy}><label className="text-sm font-semibold text-slate-800">Minimum first completed order (₦)<input className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" inputMode="numeric" value={minimumSpend || String(policy.data?.minimumFirstOrderSubtotal ?? "")} onChange={event => setMinimumSpend(event.target.value)} /></label><label className="text-sm font-semibold text-slate-800">Shopping Bonus per person (₦)<input className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" inputMode="numeric" value={bonusAmount || String(policy.data?.referralBonusAmount ?? "")} onChange={event => setBonusAmount(event.target.value)} /></label><div className="flex items-end"><button className="button button-secondary w-full" disabled={savePolicy.isPending}>{savePolicy.isPending ? "Saving…" : "Save policy"}</button></div></form>{savePolicy.error ? <p className="form-error mt-2">{savePolicy.error.message}</p> : null}</section>
    <section className="mt-4 rounded-2xl border border-amber-200 bg-amber-50/60 p-5 shadow-sm"><div className="flex items-center gap-2 text-amber-950"><ShieldCheck size={19} /><h2 className="text-base font-extrabold">Verified post-sale bonus</h2></div><p className="mt-1 text-sm leading-6 text-amber-950/75">Record only an actual cashback commitment or a verified review incentive for a delivered order. This does not publish, create, or fabricate a customer review. Every bonus remains pending through the return window.</p><form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={submitPostSaleBonus}><label className="text-sm font-semibold text-slate-800">Delivered order reference<input className="mt-1 h-11 w-full rounded-xl border border-amber-200 bg-white px-3" value={postSaleReference} onChange={event => setPostSaleReference(event.target.value)} placeholder="AC-XXXXXXXX" required /></label><label className="text-sm font-semibold text-slate-800">Bonus type<select className="mt-1 h-11 w-full rounded-xl border border-amber-200 bg-white px-3" value={postSaleType} onChange={event => setPostSaleType(event.target.value as "cashback" | "review")}><option value="cashback">Cashback</option><option value="review">Verified review incentive</option></select></label><label className="text-sm font-semibold text-slate-800">Amount (₦)<input className="mt-1 h-11 w-full rounded-xl border border-amber-200 bg-white px-3" inputMode="numeric" value={postSaleAmount} onChange={event => setPostSaleAmount(event.target.value)} placeholder="500" required /></label><div className="flex items-end"><button className="button button-secondary w-full" disabled={createPostSaleBonus.isPending}>{createPostSaleBonus.isPending ? "Queuing…" : "Create pending bonus"}</button></div></form>{createPostSaleBonus.error ? <p className="form-error mt-2">{createPostSaleBonus.error.message}</p> : null}</section>
    <section className="wallet-ledger" style={{ marginTop: 24 }}><div><span className="eyebrow">Awaiting confirmation</span><h2 className="section-title">Pending deliveries.</h2></div>{deliveries.isLoading ? <p className="loading-line">Loading orders…</p> : deliveries.error ? <div className="form-error">{deliveries.error.message}</div> : deliveries.data?.length ? <div className="wallet-ledger-list">{deliveries.data.map(order => <div className="wallet-ledger-row" key={order.reference}><div><strong>{order.reference} · {formatNaira(order.total)}</strong><span>{order.buyerName} · {order.paymentMethod === "wallet" ? "Alpha Wallet escrow" : "Pay on Delivery"} · {order.deliveryAddress}</span></div><button className="button button-primary" onClick={() => order.paymentMethod === "wallet" ? releaseWallet.mutate({ reference: order.reference }) : markDelivery.mutate({ reference: order.reference })} disabled={releaseWallet.isPending || markDelivery.isPending}><CheckCircle2 size={16} /> Mark delivered</button></div>)}</div> : <div className="empty-panel"><ShieldCheck size={24} /><h2>No orders await delivery confirmation.</h2><p>Orders will appear here after checkout.</p></div>}</section>
    <section className="wallet-ledger" style={{ marginTop: 24 }}><div><span className="eyebrow">Return window</span><h2 className="section-title">Pending rewards may still be cancelled.</h2></div>{returnWindow.isLoading ? <p className="loading-line">Loading return-window orders…</p> : returnWindow.data?.length ? <div className="wallet-ledger-list">{returnWindow.data.map(order => <div className="wallet-ledger-row" key={order.reference}><div><strong>{order.reference} · {formatNaira(order.total)}</strong><span>Delivered {order.deliveredAt ? new Date(order.deliveredAt).toLocaleString() : "recently"} · pending rewards release after 48 hours.</span></div><button className="button button-secondary" onClick={() => markReturned.mutate({ reference: order.reference })} disabled={markReturned.isPending}><RotateCcw size={16} /> Mark returned</button></div>)}</div> : <div className="empty-panel"><ShieldCheck size={24} /><h2>No pending reward returns.</h2><p>Delivered orders in their 48-hour return window appear here.</p></div>}</section>
  </div></MarketplaceShell>;
}
