import MarketplaceShell from "@/components/MarketplaceShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, KeyRound, LockKeyhole, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function DropshipIntegrations() {
  const { loading, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const integration = trpc.marketplace.admin.fulfilmentIntegration.useQuery(undefined, { enabled: isAuthenticated });
  const jobs = trpc.marketplace.admin.fulfilmentJobs.useQuery(undefined, { enabled: isAuthenticated });
  const save = trpc.marketplace.admin.saveFulfilmentIntegration.useMutation({ onSuccess: async () => { await utils.marketplace.admin.fulfilmentIntegration.invalidate(); toast.success("CJ integration settings saved."); } });
  const retry = trpc.marketplace.admin.retryFulfilmentJob.useMutation({ onSuccess: async () => { await utils.marketplace.admin.fulfilmentJobs.invalidate(); toast.success("The fulfilment job was returned to the queue."); } });
  const [enabled, setEnabled] = useState(false); const [callbackUrl, setCallbackUrl] = useState(""); const [logistics, setLogistics] = useState(""); const [fromCountry, setFromCountry] = useState(""); const [orderMode, setOrderMode] = useState<"create_only" | "balance_payment">("create_only");
  useEffect(() => { if (!integration.data) return; setEnabled(integration.data.enabled); setCallbackUrl(integration.data.callbackUrl ?? ""); setLogistics(integration.data.defaultLogisticsName ?? ""); setFromCountry(integration.data.defaultFromCountryCode ?? ""); setOrderMode(integration.data.orderMode); }, [integration.data]);
  if (loading) return <MarketplaceShell><div className="page-shell"><p className="loading-line">Checking administrator access…</p></div></MarketplaceShell>;
  if (!isAuthenticated) return <MarketplaceShell><div className="page-shell"><div className="sign-in-card"><h2>Sign in for dropship integration settings.</h2><button className="button button-primary" onClick={() => startLogin()}>Sign in <ShieldCheck size={17} /></button></div></div></MarketplaceShell>;
  if (integration.error || jobs.error) return <MarketplaceShell><div className="page-shell"><div className="sign-in-card"><h2>Administrator access required.</h2><p>Only administrators can view supplier settings and fulfilment jobs.</p></div></div></MarketplaceShell>;
  const credentialReady = integration.data?.hasServerCredential ?? false;
  return <MarketplaceShell><main className="page-shell dropship-admin-page"><section className="admin-review-hero"><div><span className="eyebrow">Administrator workspace</span><h1 className="page-title">Dropship Integrations.</h1><p className="section-kicker">CJ order automation stays off until its server credential, published callback URL, and controlled sandbox verification are complete.</p></div><a className="button button-secondary" href="/admin/official-products">Official products</a></section>
    <section className="integration-card"><div className="section-title-row"><h2>CJ Dropshipping</h2><span className={`integration-status ${credentialReady ? "is-ready" : "is-blocked"}`}><KeyRound size={14} />{credentialReady ? "Server credential present" : "Server credential required"}</span></div><p>API keys are not accepted or stored in this page. They are held only in protected server configuration and are never returned to the browser.</p><div className="admin-form-grid"><label>Default logistics name<input value={logistics} onChange={event => setLogistics(event.target.value)} placeholder="Set after CJ logistics configuration" /></label><label>Ship-from country code<input value={fromCountry} onChange={event => setFromCountry(event.target.value.toUpperCase())} maxLength={2} placeholder="CN" /></label><label>CJ callback URL (published HTTPS only)<input value={callbackUrl} onChange={event => setCallbackUrl(event.target.value)} placeholder="https://your-domain/api/webhooks/cj" /></label><label>Order mode<select value={orderMode} onChange={event => setOrderMode(event.target.value as typeof orderMode)}><option value="create_only">Create only — no CJ payment</option><option value="balance_payment">CJ balance payment</option></select></label></div><label className="integration-toggle"><input type="checkbox" checked={enabled} disabled={!credentialReady} onChange={event => setEnabled(event.target.checked)} />Enable automatic CJ fulfilment</label>{!credentialReady ? <p className="integration-warning"><AlertTriangle size={15} /> Automatic fulfilment is locked until the CJ server credential is added and validated. No supplier order can be sent.</p> : null}<button className="button button-primary" disabled={save.isPending} onClick={async () => { try { await save.mutateAsync({ enabled, callbackUrl: callbackUrl || null, defaultLogisticsName: logistics || null, defaultFromCountryCode: fromCountry || null, orderMode }); } catch (error) { toast.error(error instanceof Error ? error.message : "Settings could not be saved."); } }}><Send size={17} />Save CJ integration settings</button></section>
    <section className="fulfilment-job-list"><div className="section-title-row"><div><span className="eyebrow">Order operations</span><h2>Auto-fulfilment queue</h2></div><span className="private-source-label"><LockKeyhole size={14} /> Admin only</span></div>{jobs.isLoading ? <p className="loading-line">Loading fulfilment jobs…</p> : jobs.data?.length ? jobs.data.map(job => <article className={`fulfilment-job-row ${job.status === "manual_required" ? "is-failed" : ""}`} key={job.id}><div><span className={`fulfilment-job-badge status-${job.status}`}>{job.status === "manual_required" ? "Auto-Fulfill Failed: Requires Manual Processing" : job.status.replaceAll("_", " ")}</span><h3>{job.productTitle}</h3><p>Order {job.orderReference} · CJ Dropshipping · Qty {job.quantity}</p>{job.errorSummary ? <small>{job.errorSummary}</small> : null}</div><div className="fulfilment-job-actions"><span>{job.attemptCount} attempt{job.attemptCount === 1 ? "" : "s"}</span>{job.status === "manual_required" ? <button className="button button-secondary" disabled={retry.isPending} onClick={() => retry.mutate({ id: job.id })}><RefreshCw size={15} />Queue retry</button> : null}</div></article>) : <div className="empty-panel"><h2>No supplier jobs yet.</h2><p>Eligible paid official-product orders will appear here once CJ is activated.</p></div>}</section>
  </main></MarketplaceShell>;
}
