import MarketplaceShell from "@/components/MarketplaceShell";

type LegalPageProps = { kind: "terms" | "privacy" };

const Updated = () => <p className="legal-updated">Last updated: 25 August 2026</p>;

function Terms() {
  return <>
    <section><h2>1. Acceptance of agreement</h2><p>Welcome to Alpha Market, an online e-commerce platform, digital-wallet system, and multi-vendor marketplace operated by <strong>Alpha Collective Corporation</strong> (the “Company”, “we”, “us”, or “our”). By accessing, registering an account, depositing funds, purchasing products, listing products, or otherwise using Alpha Market, you agree to be legally bound by these Terms of Use. If you do not agree to every provision, do not access or use the platform.</p></section>
    <section><h2>2. Eligibility and user accounts</h2><p>You must be at least 18 years old, or have reached the age of legal majority in your jurisdiction, to create an account or enter a binding agreement with us. You are responsible for protecting your credentials, transaction PIN, and approved authentication methods, and for activities undertaken through your account. Notify Alpha Collective Corporation promptly through its official support channel of any suspected unauthorised access or security breach.</p></section>
    <section><h2>3. Universal KYC requirement</h2><p>Access to Alpha Wallet, including wallet balances, deposits, escrow-related payout eligibility, and withdrawals, is restricted to users with verified Know Your Customer (“KYC”) status. Subject to feature availability and applicable law, identity checks are performed through an authorized identity-verification provider. You consent to provide accurate government-issued identification and any verification information legitimately required for identity authentication. An account that is not verified may be restricted from wallet access, deposits, payout eligibility, and other protected financial functions.</p></section>
    <section><h2>4. Alpha Wallet, payments, and cryptocurrency</h2><p>Available payment methods may include approved fiat channels and, only when explicitly enabled, cryptocurrency funding through a managed provider. Crypto funding is not currently represented as a withdrawal or exchange service. Any cryptocurrency amount credited to a wallet is a non-withdrawable shopping balance: it may be used only for eligible marketplace purchases and may not be withdrawn to a bank account or external crypto wallet, except where mandatory law requires otherwise.</p><p>Where a crypto funding rail is enabled, a quoted Naira value and payment reference may be locked for up to fifteen minutes. A wallet is credited only after independent server-side provider and network verification of the expected amount, payment reference, and required confirmation status. A client-side status message, a submitted transaction hash, or a payment sent to an incorrect network is not proof of payment and does not guarantee a wallet credit.</p></section>
    <section><h2>5. Marketplace operations and fulfilment</h2><p>Alpha Market may offer products listed by independent local vendors and products fulfilled through approved dropshipping or logistics partners. Local vendors are independent sellers, not employees, agents, or partners of Alpha Collective Corporation. Certain dropshipped items may have longer delivery windows. Delivery estimates may change because of customs, carrier capacity, supplier availability, weather, or other events outside our reasonable control; reasonable order-support assistance may be provided.</p></section>
    <section><h2>6. Local Vendor Escrow</h2><p>For eligible local-vendor orders paid through an enabled Alpha Wallet escrow flow, funds are held in platform escrow rather than immediately credited to the vendor’s withdrawable balance. After an order is marked delivered, the buyer may confirm receipt and verification in the order interface. A valid buyer confirmation triggers the eligible, commission-adjusted release to the vendor. If no valid dispute or return request is recorded, a seven-day delivery fallback may release eligible funds only where the relevant scheduled safeguard is enabled. Fraud, chargebacks, returns, disputes, or legal requirements may delay, reverse, or prevent release.</p></section>
    <section><h2>7. Vendor payouts and fees</h2><p>Eligible vendor earnings may be requested to a verified Nigerian bank account through supported payout providers, subject to KYC, security review, processing rules, and availability. Alpha Collective Corporation may deduct agreed platform commissions, processing fees, refunds, reversals, chargebacks, taxes, or amounts otherwise permitted by law before a payout is finalised.</p></section>
    <section><h2>8. Intellectual property</h2><p>Alpha Market software, visual designs, brand assets, logos, interface elements, trade names, and associated content are owned by or licensed to Alpha Collective Corporation and are protected by applicable intellectual-property laws. You may not reproduce, reverse engineer, misrepresent, or exploit them without written permission, except where mandatory law permits.</p></section>
    <section><h2>9. Disclaimers and limitation of liability</h2><p>Alpha Market is provided on an “as is” and “as available” basis to the maximum extent permitted by law. We do not guarantee uninterrupted service, third-party seller performance, carrier timing, supplier availability, or blockchain-network performance. We are not responsible for user errors such as selecting an unsupported crypto network, entering inaccurate delivery details, or failing to secure account credentials. To the maximum extent permitted by law, our cumulative liability for a claim arising from a transaction will not exceed the amount paid for the specific transaction giving rise to that claim.</p></section>
    <section><h2>10. Indemnification</h2><p>You agree to indemnify and hold harmless Alpha Collective Corporation, its directors, employees, affiliates, and service providers from claims, losses, liabilities, and reasonable costs arising from your breach of these Terms, unlawful use of Alpha Market, or infringement of another person’s rights.</p></section>
    <section><h2>11. Governing law and dispute resolution</h2><p>These Terms are governed by the laws of the Federal Republic of Nigeria. Before formal proceedings, the parties should attempt good-faith resolution after written notice. Where permitted and properly initiated, unresolved disputes may be referred to arbitration under applicable Nigerian arbitration law, with Lagos State as the intended seat and English as the intended language. Mandatory consumer rights and any jurisdiction required by law are not excluded.</p></section>
    <section><h2>12. Changes and contact</h2><p>We may update these Terms to reflect legal, operational, security, or product changes. The updated version will be posted with a revised last-updated date. Alpha Market is operated by <strong>Alpha Collective Corporation</strong>. For legal questions, use the official Alpha Market support channel or the contact details published by the Company.</p></section>
  </>;
}

function Privacy() {
  return <>
    <section><h2>1. Introduction and data controller</h2><p>Alpha Collective Corporation operates Alpha Market and is responsible for the personal data described in this Privacy Policy. We process information to operate a secure marketplace, verify identity, fulfil orders, hold eligible escrow, prevent fraud, and comply with applicable Nigerian privacy, consumer, financial, and anti-money-laundering requirements.</p></section>
    <section><h2>2. Information we collect</h2><p>We may collect account and contact details; order and delivery information; product and seller information; bank or payment references; device, browser, IP, and fraud-prevention signals; support communications; and wallet, escrow, or transaction-ledger records.</p><p>When wallet or protected payment features require KYC, we collect the information needed for identity verification, such as legal name and government-ID document data. An authorised identity-verification provider may process identity-document images and verification data. If crypto funding is enabled, we may record a temporary payment address or provider reference, selected network or asset, transaction hash, quote, and confirmation status. We never ask users for private keys.</p></section>
    <section><h2>3. Legal grounds and how we use data</h2><p>We process personal data where necessary to perform a contract, meet legal obligations, protect legitimate interests such as fraud prevention and system security, or where you provide consent. We use data to provide account and marketplace functions; authenticate users; verify KYC status; process eligible orders, escrow, payouts, and payment reconciliation; calculate delivery; route fulfilment; investigate fraud or disputes; maintain security; and communicate material service events.</p></section>
    <section><h2>4. Service providers and data sharing</h2><p>We do not sell, rent, or trade personal data. We share the minimum necessary information with trusted providers and recipients that support Alpha Market:</p><div className="legal-table-wrap"><table><thead><tr><th>Provider or recipient</th><th>Purpose</th><th>Data shared when applicable</th></tr></thead><tbody><tr><td>Identity-verification provider</td><td>Identity and KYC verification</td><td>Identity-verification information and documents</td></tr><tr><td>NOWPayments or approved crypto provider</td><td>Crypto payment reference and verification</td><td>Public address or reference, payment amount, transaction status</td></tr><tr><td>Paystack or approved fiat provider</td><td>Funding, payout, or payment processing</td><td>Transaction references and bank or payment information required for the service</td></tr><tr><td>Local vendors, logistics partners, and dropshipping fulfilment providers</td><td>Order fulfilment and delivery</td><td>Recipient name, contact details, delivery address, and order details</td></tr></tbody></table></div></section>
    <section><h2>5. International transfers, security, and retention</h2><p>Some providers or fulfilment partners may process data outside Nigeria. Where this occurs, we take reasonable steps to use appropriate contractual, technical, and organisational safeguards. We use role-based access controls, server-side validation, secure transport where available, and other safeguards appropriate to the nature of the data. No online system is completely secure.</p><p>We retain data only for as long as reasonably necessary to provide services, protect users, resolve disputes, meet tax, audit, fraud-prevention, and legal obligations, or enforce agreements. Retention periods may be extended where applicable law requires it.</p></section>
    <section><h2>6. Your privacy rights</h2><p>Subject to applicable law and lawful exceptions, you may request access to, correction of, deletion of, restriction of, objection to, or portability of your personal data. Some information cannot be erased immediately where it is required for security, financial records, dispute resolution, or compliance. To make a request, contact Alpha Market through the Company’s official support channel and include enough information for us to verify the request safely.</p></section>
    <section><h2>7. Cookies and updates</h2><p>Alpha Market uses essential cookies and local browser storage for sign-in, cart, security, preference, and cookie-consent functions. You may manage browser storage through your browser settings, though essential features may work less reliably if it is disabled. We may update this Privacy Policy to reflect operational, legal, or technology changes; revised versions will be posted with an updated last-updated date.</p></section>
  </>;
}

export default function Legal({ kind }: LegalPageProps) {
  const privacy = kind === "privacy";
  return <MarketplaceShell><article className="page-shell legal-page"><span className="eyebrow">Alpha Market legal</span><h1 className="page-title">{privacy ? "Privacy Policy" : "Terms of Use"}</h1><Updated />{privacy ? <Privacy /> : <Terms />}</article></MarketplaceShell>;
}
