import MarketplaceShell from "@/components/MarketplaceShell";

type LegalPageProps = { kind: "terms" | "privacy" };

const Updated = () => <p className="legal-updated">Effective date: 25 August 2026. Draft for legal review before publication.</p>;

export default function Legal({ kind }: LegalPageProps) {
  const privacy = kind === "privacy";
  return <MarketplaceShell><article className="page-shell legal-page"><span className="eyebrow">Alpha Market legal</span><h1 className="page-title">{privacy ? "Privacy Policy" : "Terms of Use"}</h1><Updated />
    {privacy ? <>
      <section><h2>Who we are</h2><p>Alpha Market is the public marketplace operated by <strong>Alpha Collective Corporation</strong> (“we”, “us”, or “our”). This policy explains how we handle personal information when you browse, buy, sell, verify an account, or contact support through Alpha Market.</p></section>
      <section><h2>Information we collect and why</h2><p>We collect account details, order details, delivery addresses, product and seller information, device and security signals, and support communications needed to operate the marketplace, detect fraud, process orders, and meet legal obligations. We use appropriate technical and organisational safeguards, but no online system can guarantee absolute security.</p><p>Where identity verification is requested, we collect the KYC information and identity-document details needed for verification through Smile ID or a replacement verification provider. We use this information to protect wallet access, payment methods, Pay on Delivery eligibility, marketplace integrity, and compliance obligations.</p></section>
      <section><h2>Fulfilment, delivery, and service providers</h2><p>We share the minimum necessary order information, including delivery address and contact details, with local vendors, logistics partners, and approved dropshipping fulfilment providers so they can deliver an order. Supplier-facing data is limited to what is required for fulfilment; marketplace buyers do not receive our supplier sourcing details.</p></section>
      <section><h2>Wallet and crypto payment data</h2><p>If crypto wallet funding becomes available, Alpha Market may generate a temporary blockchain payment address or payment reference through an approved provider. We record the transaction reference, selected network or asset, quote, and verification status needed to reconcile a payment. We do not ask users to send private keys. Crypto payment information is handled only after server-side verification and is subject to provider and blockchain-network terms.</p></section>
      <section><h2>Cookies and choices</h2><p>We use essential cookies and local storage to provide sign-in, cart, security, preference, and cookie-consent functions. You may manage browser storage through your browser settings, although essential marketplace features may then work less reliably.</p></section>
      <section><h2>Retention, access, and contact</h2><p>We retain information only for as long as reasonably necessary for service delivery, security, disputes, tax, audit, and legal obligations. You may contact Alpha Market support to request access, correction, or deletion where applicable; some records must be retained when required by law or legitimate operational needs.</p></section>
    </> : <>
      <section><h2>Agreement and marketplace role</h2><p>These Terms govern your use of Alpha Market, the public marketplace operated by <strong>Alpha Collective Corporation</strong>. By using the platform, you agree to provide accurate information, use it lawfully, protect your account and transaction PIN, and comply with applicable laws. Independent vendors are responsible for their listings, product availability, and lawful fulfilment; Alpha Market may review, suspend, or remove accounts or listings to protect the marketplace.</p></section>
      <section><h2>Orders, delivery, and dropshipping</h2><p>Order availability, price, delivery date, and delivery route may change before fulfilment. Dropshipped products may have longer delivery timelines than local-vendor products because they are sourced and routed through logistics providers. Any stated timeline is an estimate, not a guarantee. Alpha Market may use approved fulfilment partners while presenting the consumer-facing order as an Alpha Market order.</p></section>
      <section><h2>Local Vendor Escrow</h2><p>For eligible Alpha Wallet orders from local vendors, funds are held in escrow after a successful wallet checkout. An administrator may mark an order delivered, but the vendor’s eligible escrow allocation is released only when the buyer confirms receipt or, where the buyer does not act, after the configured seven-day fallback process becomes eligible. Buyers must confirm receipt only after receiving the complete order. Fraudulent confirmations, chargebacks, returns, or disputes may delay, reverse, or prevent release where permitted by law.</p></section>
      <section><h2>Wallet and cryptocurrency funding</h2><p>Wallet funding, bank withdrawal, and crypto features are available only when enabled and verified by Alpha Market. Crypto deposits credited to the wallet are for eligible marketplace spending only and are <strong>not withdrawable to a fiat bank account</strong>. A displayed crypto quote or temporary blockchain address expires after its stated period. A wallet is credited only after server-side payment and confirmation checks; sending a transaction does not by itself guarantee a credit.</p></section>
      <section><h2>Acceptable use, limitations, and updates</h2><p>You must not manipulate referrals, evade KYC, use another person’s payment method, abuse returns, interfere with the platform, or submit unlawful, misleading, or infringing content. To the maximum extent permitted by law, Alpha Market is not liable for indirect or consequential loss, third-party provider interruptions, blockchain-network delays, or vendor acts outside our reasonable control. We may update these Terms as the marketplace evolves; continued use after an effective update indicates acceptance where legally permitted.</p></section>
      <section><h2>Contact and governing requirements</h2><p>Questions, complaints, or requests about these Terms should be sent through Alpha Market support. These Terms are intended to operate alongside applicable Nigerian consumer, privacy, payments, and commerce requirements; mandatory legal rights are not excluded.</p></section>
    </>}
  </article></MarketplaceShell>;
}
