import MarketplaceShell from "@/components/MarketplaceShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { displayWalletAmount, WALLET_BALANCE_PRIVACY_KEY } from "@/lib/walletPrivacy";
import { formatNaira } from "@shared/marketplace";
import { ArrowRight, BadgeCheck, Bitcoin, Building2, ChevronDown, CircleAlert, Copy, Eye, EyeOff, Landmark, Loader2, LockKeyhole, PlusCircle, ShieldCheck, WalletCards } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const labels = { deposit: "Deposit", withdrawal: "Withdrawal", purchase_escrow: "Purchase (Escrow)", bonus_purchase: "Shopping Bonus (Purchase)", refund: "Refund", sale_earning: "Sale Earning", reward_bonus: "Shopping Bonus (Reward)" } as const;
const withdrawalLabels = { pending: "Requested", processing: "Processing", paid: "Paid", rejected: "Rejected", failed: "Restored", reversed: "Reversed & restored", cancelled: "Cancelled" } as const;
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100 disabled:cursor-not-allowed disabled:bg-slate-100";

function asWholeNaira(value: string) {
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : null;
}

export default function Wallet() {
  const { isAuthenticated, loading, user } = useAuth();
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const wallet = trpc.marketplace.wallet.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const kyc = trpc.marketplace.kyc.status.useQuery(undefined, { enabled: isAuthenticated });
  const banks = trpc.marketplace.wallet.listBanks.useQuery(undefined, { enabled: isAuthenticated });
  const [pin, setPinValue] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [fundingAmount, setFundingAmount] = useState("");
  const [fundingEmail, setFundingEmail] = useState(user?.email ?? "");
  const [showFunding, setShowFunding] = useState(false);
  const [cryptoAmount, setCryptoAmount] = useState("");
  const [cryptoCurrency, setCryptoCurrency] = useState("usdttrc20");
  const [cryptoQuote, setCryptoQuote] = useState<{ reference: string; payAddress: string; payAmount: string; payCurrency: string; quoteExpiresAt: Date } | null>(null);
  const [bankCode, setBankCode] = useState("");
  const [accountNumber, setAccountNumber] = useState("");
  const [showBankForm, setShowBankForm] = useState(false);
  const [withdrawalAmount, setWithdrawalAmount] = useState("");
  const [withdrawalPin, setWithdrawalPin] = useState("");
  const [withdrawalConfirmed, setWithdrawalConfirmed] = useState(false);
  const [showWithdrawal, setShowWithdrawal] = useState(false);
  const [balancesHidden, setBalancesHidden] = useState(() => {
    try { return window.localStorage.getItem(WALLET_BALANCE_PRIVACY_KEY) === "true"; } catch { return false; }
  });
  const toggleBalances = () => setBalancesHidden(current => {
    const next = !current;
    try { window.localStorage.setItem(WALLET_BALANCE_PRIVACY_KEY, String(next)); } catch { /* Storage is optional for this display preference. */ }
    return next;
  });
  const walletAmount = (amount: number) => displayWalletAmount(amount, balancesHidden);
  const invalidateWallet = async () => { await Promise.all([utils.marketplace.wallet.dashboard.invalidate(), utils.marketplace.wallet.listBanks.invalidate()]); };
  const setWalletPin = trpc.marketplace.wallet.setPin.useMutation({ onSuccess: async () => { setPinValue(""); setConfirmation(""); await invalidateWallet(); toast.success("Your transaction PIN is ready."); } });
  const verifyBankAccount = trpc.marketplace.wallet.verifyBankAccount.useMutation({ onSuccess: async result => { setAccountNumber(""); setShowBankForm(false); await invalidateWallet(); toast.success(`${result.bankName} account verified for ${result.accountName}.`); } });
  const initializeFunding = trpc.marketplace.wallet.initializeFunding.useMutation({ onSuccess: result => { toast.message("Opening Paystack’s secure payment page. Your wallet will update only after Paystack verification."); window.location.assign(result.authorizationUrl); } });
  const createCryptoTestQuote = trpc.marketplace.wallet.createCryptoTestQuote.useMutation({ onSuccess: result => { setCryptoQuote(result); toast.success("Controlled crypto quote created. Your wallet stays unchanged until NOWPayments independently confirms payment."); } });
  const requestWithdrawal = trpc.marketplace.wallet.requestWithdrawal.useMutation({ onSuccess: async result => { setWithdrawalAmount(""); setWithdrawalPin(""); setWithdrawalConfirmed(false); setShowWithdrawal(false); await invalidateWallet(); toast.error(result.otpDelivery === "unavailable" ? "Withdrawal OTP email delivery is not configured yet. No bank transfer was started." : "Your withdrawal requires an emailed OTP before it can proceed."); } });
  const confirmDelivery = trpc.marketplace.wallet.confirmDelivery.useMutation({ onSuccess: async () => { await invalidateWallet(); toast.success("Receipt confirmed. The local vendor’s escrow release is now being recorded."); } });

  const submitPin = (event: FormEvent) => { event.preventDefault(); setWalletPin.mutate({ pin, confirmation }); };
  const submitBank = (event: FormEvent) => { event.preventDefault(); if (!bankCode || accountNumber.length !== 10) return toast.error("Select your bank and enter its 10-digit account number."); verifyBankAccount.mutate({ bankCode, accountNumber }); };
  const submitFunding = (event: FormEvent) => { event.preventDefault(); const amount = asWholeNaira(fundingAmount); if (!amount || amount < 100) return toast.error("Enter a whole-Naira amount of at least ₦100."); initializeFunding.mutate({ amount, email: fundingEmail.trim() }); };
  const submitCryptoQuote = (event: FormEvent) => { event.preventDefault(); const amount = asWholeNaira(cryptoAmount); if (!amount || amount < 100 || amount > 500) return toast.error("Controlled live crypto testing is limited to ₦100–₦500."); createCryptoTestQuote.mutate({ amount, payCurrency: cryptoCurrency }); };
  const submitWithdrawal = (event: FormEvent) => { event.preventDefault(); const amount = asWholeNaira(withdrawalAmount); if (!amount || amount < 100) return toast.error("Enter a whole-Naira amount of at least ₦100."); if (!withdrawalConfirmed) return toast.error("Confirm that you want to send this amount to your verified account."); requestWithdrawal.mutate({ amount, transactionPin: withdrawalPin, confirmed: true }); };
  useEffect(() => {
    if (isAuthenticated && kyc.data && kyc.data.status !== "verified") setLocation("/kyc");
  }, [isAuthenticated, kyc.data, setLocation]);

  if (loading) return <MarketplaceShell><div className="page-shell"><p className="loading-line">Loading your wallet…</p></div></MarketplaceShell>;
  if (!isAuthenticated) return <MarketplaceShell><div className="page-shell"><div className="sign-in-card" style={{ marginTop: 36 }}><WalletCards size={28} /><h1>Your Alpha Wallet.</h1><p>Sign in to view your balance, secure your PIN, and manage internal marketplace payments.</p><button className="button button-primary" onClick={() => startLogin()}>Sign in to continue <ArrowRight size={17} /></button></div></div></MarketplaceShell>;
  if (kyc.isLoading || !kyc.data) return <MarketplaceShell><div className="page-shell"><p className="loading-line">Checking KYC access…</p></div></MarketplaceShell>;
  if (kyc.data.status !== "verified") return <MarketplaceShell><div className="page-shell"><div className="sign-in-card"><ShieldCheck size={28} /><h1>KYC verification required.</h1><p>Alpha Wallet is available after your identity has been verified. Taking you to the verification workspace…</p></div></div></MarketplaceShell>;
  const data = wallet.data;

  return <MarketplaceShell><div className="page-shell pb-12">
    <section className="wallet-hero"><div className="flex items-start justify-between gap-3"><div><span className="eyebrow">Alpha Wallet</span><h1 className="page-title">Your marketplace balance.</h1></div><button type="button" className="wallet-privacy-toggle shrink-0" onClick={toggleBalances} aria-pressed={balancesHidden} aria-label={balancesHidden ? "Reveal wallet balances" : "Hide wallet balances"}>{balancesHidden ? <Eye size={17} /> : <EyeOff size={17} />}{balancesHidden ? "Reveal" : "Hide"}</button></div><p>Shopping Bonus is used first at checkout. Only your withdrawable cash may be transferred to your verified bank.</p><div className="wallet-balances"><div><span>Total balance</span><strong>{data ? walletAmount(data.totalBalance) : "Loading…"}</strong></div><div title="Cash available to transfer to your bank."><span>Withdrawable balance</span><strong>{data ? walletAmount(data.withdrawableBalance) : "Loading…"}</strong><small>Cash available to transfer to your bank.</small></div><div title="Reward cash for purchases on Alpha Market. It cannot be withdrawn."><span>Shopping Bonus</span><strong>{data ? walletAmount(data.bonusBalance) : "Loading…"}</strong><small>Reward cash for Alpha Market purchases only.</small></div><div><span>Pending rewards</span><strong>{data ? walletAmount(data.pendingBonusBalance) : "Loading…"}</strong><small>Available after the 48-hour return window.</small></div><div><span>Held in escrow</span><strong>{data ? walletAmount(data.escrowBalance) : "Loading…"}</strong></div></div></section>
    {data?.pendingRewards.length ? <section className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><span className="eyebrow">Pending Shopping Bonus</span><h2 className="mt-1 text-base font-extrabold text-amber-950">Awaiting the return window.</h2><div className="mt-3 space-y-2">{data.pendingRewards.map(reward => <div className="flex items-center justify-between gap-3 rounded-xl bg-white/80 px-3 py-2 text-sm" key={reward.id}><span className="font-semibold text-amber-950">{reward.type === "referral" ? "Referral bonus" : reward.type === "cashback" ? "Cashback bonus" : "Review bonus"}</span><span className="text-right text-amber-900">{walletAmount(reward.amount)} · releases {new Date(reward.releaseAt).toLocaleString()}</span></div>)}</div></section> : null}
    {!data?.hasPin ? <section className="wallet-pin-card"><LockKeyhole size={22} /><div><span className="eyebrow">Security required</span><h2>Set your 4-digit transaction PIN.</h2><p>You will need this PIN for wallet purchases and withdrawals. It is stored only as a secure server-side hash.</p><form onSubmit={submitPin} className="form-grid"><input aria-label="New transaction PIN" inputMode="numeric" type="password" pattern="\d{4}" maxLength={4} value={pin} onChange={event => setPinValue(event.target.value.replace(/\D/g, ""))} placeholder="New PIN" required /><input aria-label="Confirm transaction PIN" inputMode="numeric" type="password" pattern="\d{4}" maxLength={4} value={confirmation} onChange={event => setConfirmation(event.target.value.replace(/\D/g, ""))} placeholder="Confirm PIN" required /><button className="button button-primary" disabled={setWalletPin.isPending || pin.length !== 4 || confirmation.length !== 4}>{setWalletPin.isPending ? "Securing…" : "Secure my wallet"}</button></form>{setWalletPin.error ? <p className="form-error">{setWalletPin.error.message}</p> : null}</div></section> : null}

    <section className="mt-6 grid gap-4 lg:grid-cols-2">
      <article className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-emerald-800"><PlusCircle size={19} /><span className="text-sm font-bold">Fund your wallet</span></div><p className="mt-2 text-sm leading-6 text-emerald-950/75">Pay through Paystack. Your balance changes only after the verified Paystack payment is received.</p></div><ShieldCheck className="shrink-0 text-emerald-700" size={24} /></div><button className="button button-primary mt-4" onClick={() => setShowFunding(value => !value)} disabled={!data?.hasPin}>{showFunding ? "Close funding form" : "Fund Wallet"}</button>{!data?.hasPin ? <p className="mt-3 text-xs font-medium text-emerald-900">Set your transaction PIN before funding and spending with Alpha Wallet.</p> : null}
        {showFunding ? <form className="mt-4 space-y-3 border-t border-emerald-200 pt-4" onSubmit={submitFunding}><label className="block text-sm font-semibold text-slate-800">Amount in Naira<input className={`${inputClass} mt-1`} inputMode="numeric" min="100" step="1" type="number" value={fundingAmount} onChange={event => setFundingAmount(event.target.value)} placeholder="e.g. 25000" required /></label><label className="block text-sm font-semibold text-slate-800">Payment receipt email<input className={`${inputClass} mt-1`} type="email" value={fundingEmail} onChange={event => setFundingEmail(event.target.value)} placeholder="you@example.com" required /></label><p className="flex gap-2 text-xs leading-5 text-slate-600"><CircleAlert size={15} className="mt-0.5 shrink-0" />You will continue to Paystack’s secure payment page. Do not close the page until Paystack confirms your payment.</p><button className="button button-primary w-full" disabled={initializeFunding.isPending}>{initializeFunding.isPending ? <><Loader2 className="animate-spin" size={16} /> Opening Paystack…</> : "Continue to Paystack"}</button>{initializeFunding.error ? <p className="form-error">{initializeFunding.error.message}</p> : null}</form> : null}
      </article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-slate-800"><Landmark size={19} /><span className="text-sm font-bold">Verified Nigerian bank account</span></div><p className="mt-2 text-sm leading-6 text-slate-600">Your full account number is used only to verify and register a Paystack recipient. Alpha Wallet stores only a masked account number.</p></div><Building2 className="shrink-0 text-slate-500" size={24} /></div>
        {data?.recipient ? <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center gap-2 text-sm font-bold text-slate-800"><BadgeCheck size={17} className="text-emerald-600" />Verified recipient</div><p className="mt-1 text-sm text-slate-700">{data.recipient.bankName} · {data.recipient.accountNumberMasked}</p><p className="text-xs text-slate-500">{data.recipient.accountName}</p><button className="mt-3 text-sm font-bold text-emerald-700 underline underline-offset-4" onClick={() => setShowBankForm(value => !value)}>{showBankForm ? "Cancel change" : "Use another bank account"}</button></div> : <button className="button button-secondary mt-4" onClick={() => setShowBankForm(true)}>Verify a bank account <ChevronDown size={16} /></button>}
        {showBankForm ? <form className="mt-4 space-y-3 border-t border-slate-200 pt-4" onSubmit={submitBank}><label className="block text-sm font-semibold text-slate-800">Bank<select className={`${inputClass} mt-1`} value={bankCode} onChange={event => setBankCode(event.target.value)} disabled={banks.isLoading || verifyBankAccount.isPending} required><option value="">{banks.isLoading ? "Loading Nigerian banks…" : "Select your bank"}</option>{banks.data?.map(bank => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</select></label><label className="block text-sm font-semibold text-slate-800">10-digit account number<input className={`${inputClass} mt-1`} inputMode="numeric" maxLength={10} value={accountNumber} onChange={event => setAccountNumber(event.target.value.replace(/\D/g, "").slice(0, 10))} placeholder="0123456789" required /></label><p className="text-xs leading-5 text-slate-600">Confirm the returned account holder name carefully. This action does not send money.</p><button className="button button-secondary w-full" disabled={verifyBankAccount.isPending || banks.isLoading}>{verifyBankAccount.isPending ? <><Loader2 className="animate-spin" size={16} /> Verifying…</> : "Verify bank account"}</button>{banks.error ? <p className="form-error">{banks.error.message}</p> : null}{verifyBankAccount.error ? <p className="form-error">{verifyBankAccount.error.message}</p> : null}</form> : null}
      </article>
    </section>
    <section className="mt-4 rounded-2xl border border-violet-200 bg-violet-50/70 p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-violet-950"><Bitcoin size={19} /><span className="text-sm font-bold">Controlled crypto funding test</span></div><p className="mt-2 text-sm leading-6 text-violet-950/75">Create a live NOWPayments quote of up to ₦500. Do not send funds to any other address. A confirmed amount becomes Shopping Bonus only and cannot be withdrawn to a bank or crypto wallet.</p></div><ShieldCheck className="shrink-0 text-violet-700" size={24} /></div><form className="mt-4 grid gap-3 border-t border-violet-200 pt-4 sm:grid-cols-2" onSubmit={submitCryptoQuote}><label className="block text-sm font-semibold text-slate-800">Test amount in Naira (₦100–₦500)<input className={`${inputClass} mt-1`} inputMode="numeric" min="100" max="500" step="1" type="number" value={cryptoAmount} onChange={event => setCryptoAmount(event.target.value)} required /></label><label className="block text-sm font-semibold text-slate-800">Asset<select className={`${inputClass} mt-1`} value={cryptoCurrency} onChange={event => setCryptoCurrency(event.target.value)}><option value="usdttrc20">USDT (TRC20)</option><option value="btc">Bitcoin</option></select></label><p className="sm:col-span-2 flex gap-2 text-xs leading-5 text-violet-950/80"><CircleAlert size={15} className="mt-0.5 shrink-0" />The quote expires after 15 minutes. A browser success message is not proof of payment; the server checks NOWPayments again before any Shopping Bonus credit.</p><div className="sm:col-span-2"><button className="button button-secondary" disabled={createCryptoTestQuote.isPending || !data?.hasPin}>{createCryptoTestQuote.isPending ? <><Loader2 className="animate-spin" size={16} /> Creating protected quote…</> : "Create ₦500-or-less crypto quote"}</button>{createCryptoTestQuote.error ? <p className="form-error mt-2">{createCryptoTestQuote.error.message}</p> : null}</div></form>{cryptoQuote ? <div className="mt-4 rounded-xl border border-violet-200 bg-white p-4 text-sm text-slate-800"><div className="flex items-center justify-between gap-3"><strong>Send exactly {cryptoQuote.payAmount} {cryptoQuote.payCurrency.toUpperCase()}</strong><button type="button" className="text-violet-700" aria-label="Copy crypto payment address" onClick={() => { void navigator.clipboard.writeText(cryptoQuote.payAddress); toast.success("Crypto payment address copied."); }}><Copy size={17} /></button></div><code className="mt-3 block break-all rounded-lg bg-slate-50 p-3 text-xs text-slate-700">{cryptoQuote.payAddress}</code><p className="mt-3 text-xs leading-5 text-slate-600">Reference: {cryptoQuote.reference}. Quote expires {new Date(cryptoQuote.quoteExpiresAt).toLocaleString()}. No wallet credit occurs until NOWPayments reports and the server independently verifies a finished payment.</p></div> : null}</section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-slate-800"><Landmark size={19} /><h2 className="text-base font-extrabold">Withdraw to your verified bank</h2></div><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">Only the withdrawable balance is eligible for a bank transfer. Shopping Bonus cannot be withdrawn. A withdrawal also requires a KYC-locked bank account, your transaction PIN, and an emailed six-digit OTP.</p></div><button className="button button-secondary shrink-0" disabled={!data?.hasPin || !data?.recipient || kyc.data?.status !== "verified" || data.recipient?.kycBindingStatus !== "locked"} onClick={() => setShowWithdrawal(value => !value)}>{showWithdrawal ? "Close withdrawal form" : "Withdraw Funds"}</button></div>
      {!data?.recipient ? <p className="mt-3 text-xs font-medium text-amber-800">Verify a Nigerian bank account above before requesting a withdrawal.</p> : kyc.data?.status !== "verified" || data.recipient.kycBindingStatus !== "locked" ? <p className="mt-3 text-xs font-medium text-amber-800">Complete KYC Verification and legal-name bank matching before requesting a withdrawal.</p> : null}
      {showWithdrawal ? <form className="mt-5 grid gap-3 border-t border-slate-200 pt-5 md:grid-cols-2" onSubmit={submitWithdrawal}><label className="block text-sm font-semibold text-slate-800">Amount in Naira <span className="text-xs font-normal text-slate-500">(up to {walletAmount(data?.withdrawableBalance ?? 0)})</span><input className={`${inputClass} mt-1`} inputMode="numeric" min="100" max={data?.withdrawableBalance ?? 0} step="1" type="number" value={withdrawalAmount} onChange={event => setWithdrawalAmount(event.target.value)} placeholder="e.g. 15000" required /></label><label className="block text-sm font-semibold text-slate-800">4-digit transaction PIN<input className={`${inputClass} mt-1`} type="password" inputMode="numeric" pattern="\d{4}" maxLength={4} value={withdrawalPin} onChange={event => setWithdrawalPin(event.target.value.replace(/\D/g, ""))} placeholder="••••" required /></label><label className="md:col-span-2 flex cursor-pointer items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm leading-5 text-amber-950"><input className="mt-1 size-4 accent-emerald-700" type="checkbox" checked={withdrawalConfirmed} onChange={event => setWithdrawalConfirmed(event.target.checked)} /><span>I confirm that I want to transfer the entered amount to <strong>{data?.recipient?.bankName} · {data?.recipient?.accountNumberMasked}</strong>. Shopping Bonus will not be used. This request cannot be cancelled after Paystack processes it.</span></label><div className="md:col-span-2"><button className="button button-primary" disabled={requestWithdrawal.isPending || withdrawalPin.length !== 4 || !withdrawalConfirmed}>{requestWithdrawal.isPending ? <><Loader2 className="animate-spin" size={16} /> Requesting transfer…</> : "Confirm bank withdrawal"}</button>{requestWithdrawal.error ? <p className="form-error mt-2">{requestWithdrawal.error.message}</p> : null}</div></form> : null}
      {data?.withdrawals.length ? <div className="mt-5 border-t border-slate-100 pt-4"><h3 className="text-sm font-extrabold text-slate-800">Recent withdrawal requests</h3><div className="mt-2 space-y-2">{data.withdrawals.slice(0, 3).map(request => <div className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm" key={request.id}><span className="font-semibold text-slate-700">{walletAmount(request.amount)}</span><span className="text-slate-500">{withdrawalLabels[request.status]}</span></div>)}</div></div> : null}
    </section>
    {data?.escrowOrders.length ? <section className="mt-4 rounded-2xl border border-emerald-100 bg-emerald-50/60 p-5 shadow-sm"><span className="eyebrow">Order receipt</span><h2 className="mt-1 text-base font-extrabold text-emerald-950">Confirm a local-vendor delivery.</h2><p className="mt-1 text-sm leading-6 text-emerald-950/75">Confirm only after you have received the complete order. This releases the held escrow to the local vendor and cannot be undone here.</p><div className="mt-4 space-y-3">{data.escrowOrders.map(order => <div className="flex flex-col justify-between gap-3 rounded-xl border border-emerald-100 bg-white p-3 sm:flex-row sm:items-center" key={order.reference}><div><strong className="text-sm text-slate-900">{order.reference} · {formatNaira(order.total)}</strong><p className="mt-1 text-xs text-slate-600">{order.fulfillmentStatus === "delivered" ? "Delivery marked by Alpha Market." : "Awaiting delivery confirmation."}</p></div>{order.localVendorOrder && order.fulfillmentStatus === "delivered" && !order.buyerConfirmedAt ? <button className="button button-primary shrink-0" onClick={() => confirmDelivery.mutate({ reference: order.reference })} disabled={confirmDelivery.isPending}>{confirmDelivery.isPending ? "Confirming…" : "Confirm receipt"}</button> : null}</div>)}</div>{confirmDelivery.error ? <p className="form-error mt-3">{confirmDelivery.error.message}</p> : null}</section> : null}
    <section className="wallet-ledger"><div><span className="eyebrow">Transaction ledger</span><h2 className="section-title">Money in and out.</h2></div>{wallet.isLoading ? <p className="loading-line">Loading transactions…</p> : data?.transactions.length ? <div className="wallet-ledger-list">{data.transactions.map(entry => <div className="wallet-ledger-row" key={entry.id}><div><strong>{labels[entry.type]}</strong><span>{entry.description} · {entry.status}</span></div><strong className={entry.direction === "in" ? "wallet-money-in" : "wallet-money-out"}>{entry.direction === "in" ? "+" : "−"}{walletAmount(entry.amount)}</strong></div>)}</div> : <div className="empty-panel"><h3>No wallet activity yet.</h3><p>Once Paystack verifies a funding payment or you complete a wallet order, your activity will appear here.</p></div>}</section>
  </div></MarketplaceShell>;
}
