import MarketplaceShell from "@/components/MarketplaceShell";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { formatNaira } from "@shared/marketplace";
import { ArrowRight, BadgeCheck, Building2, ChevronDown, CircleAlert, Landmark, Loader2, LockKeyhole, PlusCircle, ShieldCheck, WalletCards } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const labels = { deposit: "Deposit", withdrawal: "Withdrawal", purchase_escrow: "Purchase (Escrow)", refund: "Refund", sale_earning: "Sale Earning" } as const;
const withdrawalLabels = { pending: "Requested", processing: "Processing", paid: "Paid", rejected: "Rejected", failed: "Restored", reversed: "Reversed & restored", cancelled: "Cancelled" } as const;
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100 disabled:cursor-not-allowed disabled:bg-slate-100";

function asWholeNaira(value: string) {
  const parsed = Number(value);
  return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : null;
}

export default function Wallet() {
  const { isAuthenticated, loading, user } = useAuth();
  const utils = trpc.useUtils();
  const wallet = trpc.marketplace.wallet.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const banks = trpc.marketplace.wallet.listBanks.useQuery(undefined, { enabled: isAuthenticated });
  const [pin, setPinValue] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [fundingAmount, setFundingAmount] = useState("");
  const [fundingEmail, setFundingEmail] = useState(user?.email ?? "");
  const [showFunding, setShowFunding] = useState(false);
  const [bankCode, setBankCode] = useState("");
  const [accountNumber, setAccountNumber] = useState("");
  const [showBankForm, setShowBankForm] = useState(false);
  const [withdrawalAmount, setWithdrawalAmount] = useState("");
  const [withdrawalPin, setWithdrawalPin] = useState("");
  const [withdrawalConfirmed, setWithdrawalConfirmed] = useState(false);
  const [showWithdrawal, setShowWithdrawal] = useState(false);
  const invalidateWallet = async () => { await Promise.all([utils.marketplace.wallet.dashboard.invalidate(), utils.marketplace.wallet.listBanks.invalidate()]); };
  const setWalletPin = trpc.marketplace.wallet.setPin.useMutation({ onSuccess: async () => { setPinValue(""); setConfirmation(""); await invalidateWallet(); toast.success("Your transaction PIN is ready."); } });
  const verifyBankAccount = trpc.marketplace.wallet.verifyBankAccount.useMutation({ onSuccess: async result => { setAccountNumber(""); setShowBankForm(false); await invalidateWallet(); toast.success(`${result.bankName} account verified for ${result.accountName}.`); } });
  const initializeFunding = trpc.marketplace.wallet.initializeFunding.useMutation({ onSuccess: result => { toast.message("Opening Paystack’s secure payment page. Your wallet will update only after Paystack verification."); window.location.assign(result.authorizationUrl); } });
  const requestWithdrawal = trpc.marketplace.wallet.requestWithdrawal.useMutation({ onSuccess: async result => { setWithdrawalAmount(""); setWithdrawalPin(""); setWithdrawalConfirmed(false); setShowWithdrawal(false); await invalidateWallet(); toast.success(result.pendingProviderConfirmation ? "Your bank transfer request is processing. The balance remains safeguarded until Paystack confirms the result." : "Your bank transfer request is processing. Paystack will confirm the result shortly."); } });

  const submitPin = (event: FormEvent) => { event.preventDefault(); setWalletPin.mutate({ pin, confirmation }); };
  const submitBank = (event: FormEvent) => { event.preventDefault(); if (!bankCode || accountNumber.length !== 10) return toast.error("Select your bank and enter its 10-digit account number."); verifyBankAccount.mutate({ bankCode, accountNumber }); };
  const submitFunding = (event: FormEvent) => { event.preventDefault(); const amount = asWholeNaira(fundingAmount); if (!amount || amount < 100) return toast.error("Enter a whole-Naira amount of at least ₦100."); initializeFunding.mutate({ amount, email: fundingEmail.trim() }); };
  const submitWithdrawal = (event: FormEvent) => { event.preventDefault(); const amount = asWholeNaira(withdrawalAmount); if (!amount || amount < 100) return toast.error("Enter a whole-Naira amount of at least ₦100."); if (!withdrawalConfirmed) return toast.error("Confirm that you want to send this amount to your verified account."); requestWithdrawal.mutate({ amount, transactionPin: withdrawalPin, confirmed: true }); };

  if (loading) return <MarketplaceShell><div className="page-shell"><p className="loading-line">Loading your wallet…</p></div></MarketplaceShell>;
  if (!isAuthenticated) return <MarketplaceShell><div className="page-shell"><div className="sign-in-card" style={{ marginTop: 36 }}><WalletCards size={28} /><h1>Your Alpha Wallet.</h1><p>Sign in to view your balance, secure your PIN, and manage internal marketplace payments.</p><button className="button button-primary" onClick={() => startLogin()}>Sign in to continue <ArrowRight size={17} /></button></div></div></MarketplaceShell>;
  const data = wallet.data;

  return <MarketplaceShell><div className="page-shell pb-12">
    <section className="wallet-hero"><span className="eyebrow">Alpha Wallet</span><h1 className="page-title">Your marketplace balance.</h1><p>Available funds can pay other sellers. Wallet purchases are held in escrow until delivery is confirmed.</p><div className="wallet-balances"><div><span>Available balance</span><strong>{data ? formatNaira(data.availableBalance) : "Loading…"}</strong></div><div><span>Held in escrow</span><strong>{data ? formatNaira(data.escrowBalance) : "Loading…"}</strong></div></div></section>
    {!data?.hasPin ? <section className="wallet-pin-card"><LockKeyhole size={22} /><div><span className="eyebrow">Security required</span><h2>Set your 4-digit transaction PIN.</h2><p>You will need this PIN for wallet purchases and withdrawals. It is stored only as a secure server-side hash.</p><form onSubmit={submitPin} className="form-grid"><input aria-label="New transaction PIN" inputMode="numeric" type="password" pattern="\d{4}" maxLength={4} value={pin} onChange={event => setPinValue(event.target.value.replace(/\D/g, ""))} placeholder="New PIN" required /><input aria-label="Confirm transaction PIN" inputMode="numeric" type="password" pattern="\d{4}" maxLength={4} value={confirmation} onChange={event => setConfirmation(event.target.value.replace(/\D/g, ""))} placeholder="Confirm PIN" required /><button className="button button-primary" disabled={setWalletPin.isPending || pin.length !== 4 || confirmation.length !== 4}>{setWalletPin.isPending ? "Securing…" : "Secure my wallet"}</button></form>{setWalletPin.error ? <p className="form-error">{setWalletPin.error.message}</p> : null}</div></section> : null}

    <section className="mt-6 grid gap-4 lg:grid-cols-2">
      <article className="rounded-2xl border border-emerald-100 bg-emerald-50/70 p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-emerald-800"><PlusCircle size={19} /><span className="text-sm font-bold">Fund your wallet</span></div><p className="mt-2 text-sm leading-6 text-emerald-950/75">Pay through Paystack. Your balance changes only after the verified Paystack payment is received.</p></div><ShieldCheck className="shrink-0 text-emerald-700" size={24} /></div><button className="button button-primary mt-4" onClick={() => setShowFunding(value => !value)} disabled={!data?.hasPin}>{showFunding ? "Close funding form" : "Fund Wallet"}</button>{!data?.hasPin ? <p className="mt-3 text-xs font-medium text-emerald-900">Set your transaction PIN before funding and spending with Alpha Wallet.</p> : null}
        {showFunding ? <form className="mt-4 space-y-3 border-t border-emerald-200 pt-4" onSubmit={submitFunding}><label className="block text-sm font-semibold text-slate-800">Amount in Naira<input className={`${inputClass} mt-1`} inputMode="numeric" min="100" step="1" type="number" value={fundingAmount} onChange={event => setFundingAmount(event.target.value)} placeholder="e.g. 25000" required /></label><label className="block text-sm font-semibold text-slate-800">Payment receipt email<input className={`${inputClass} mt-1`} type="email" value={fundingEmail} onChange={event => setFundingEmail(event.target.value)} placeholder="you@example.com" required /></label><p className="flex gap-2 text-xs leading-5 text-slate-600"><CircleAlert size={15} className="mt-0.5 shrink-0" />You will continue to Paystack’s secure payment page. Do not close the page until Paystack confirms your payment.</p><button className="button button-primary w-full" disabled={initializeFunding.isPending}>{initializeFunding.isPending ? <><Loader2 className="animate-spin" size={16} /> Opening Paystack…</> : "Continue to Paystack"}</button>{initializeFunding.error ? <p className="form-error">{initializeFunding.error.message}</p> : null}</form> : null}
      </article>
      <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-slate-800"><Landmark size={19} /><span className="text-sm font-bold">Verified Nigerian bank account</span></div><p className="mt-2 text-sm leading-6 text-slate-600">Your full account number is used only to verify and register a Paystack recipient. Alpha Wallet stores only a masked account number.</p></div><Building2 className="shrink-0 text-slate-500" size={24} /></div>
        {data?.recipient ? <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center gap-2 text-sm font-bold text-slate-800"><BadgeCheck size={17} className="text-emerald-600" />Verified recipient</div><p className="mt-1 text-sm text-slate-700">{data.recipient.bankName} · {data.recipient.accountNumberMasked}</p><p className="text-xs text-slate-500">{data.recipient.accountName}</p><button className="mt-3 text-sm font-bold text-emerald-700 underline underline-offset-4" onClick={() => setShowBankForm(value => !value)}>{showBankForm ? "Cancel change" : "Use another bank account"}</button></div> : <button className="button button-secondary mt-4" onClick={() => setShowBankForm(true)}>Verify a bank account <ChevronDown size={16} /></button>}
        {showBankForm ? <form className="mt-4 space-y-3 border-t border-slate-200 pt-4" onSubmit={submitBank}><label className="block text-sm font-semibold text-slate-800">Bank<select className={`${inputClass} mt-1`} value={bankCode} onChange={event => setBankCode(event.target.value)} disabled={banks.isLoading || verifyBankAccount.isPending} required><option value="">{banks.isLoading ? "Loading Nigerian banks…" : "Select your bank"}</option>{banks.data?.map(bank => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</select></label><label className="block text-sm font-semibold text-slate-800">10-digit account number<input className={`${inputClass} mt-1`} inputMode="numeric" maxLength={10} value={accountNumber} onChange={event => setAccountNumber(event.target.value.replace(/\D/g, "").slice(0, 10))} placeholder="0123456789" required /></label><p className="text-xs leading-5 text-slate-600">Confirm the returned account holder name carefully. This action does not send money.</p><button className="button button-secondary w-full" disabled={verifyBankAccount.isPending || banks.isLoading}>{verifyBankAccount.isPending ? <><Loader2 className="animate-spin" size={16} /> Verifying…</> : "Verify bank account"}</button>{banks.error ? <p className="form-error">{banks.error.message}</p> : null}{verifyBankAccount.error ? <p className="form-error">{verifyBankAccount.error.message}</p> : null}</form> : null}
      </article>
    </section>
    <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-slate-800"><Landmark size={19} /><h2 className="text-base font-extrabold">Withdraw to your verified bank</h2></div><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">A withdrawal begins only after you enter your transaction PIN and explicitly confirm the transfer. Your balance is restored if Paystack reports that the transfer failed or was reversed.</p></div><button className="button button-secondary shrink-0" disabled={!data?.hasPin || !data?.recipient} onClick={() => setShowWithdrawal(value => !value)}>{showWithdrawal ? "Close withdrawal form" : "Withdraw Funds"}</button></div>
      {!data?.recipient ? <p className="mt-3 text-xs font-medium text-amber-800">Verify a Nigerian bank account above before requesting a withdrawal.</p> : null}
      {showWithdrawal ? <form className="mt-5 grid gap-3 border-t border-slate-200 pt-5 md:grid-cols-2" onSubmit={submitWithdrawal}><label className="block text-sm font-semibold text-slate-800">Amount in Naira<input className={`${inputClass} mt-1`} inputMode="numeric" min="100" step="1" type="number" value={withdrawalAmount} onChange={event => setWithdrawalAmount(event.target.value)} placeholder="e.g. 15000" required /></label><label className="block text-sm font-semibold text-slate-800">4-digit transaction PIN<input className={`${inputClass} mt-1`} type="password" inputMode="numeric" pattern="\d{4}" maxLength={4} value={withdrawalPin} onChange={event => setWithdrawalPin(event.target.value.replace(/\D/g, ""))} placeholder="••••" required /></label><label className="md:col-span-2 flex cursor-pointer items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm leading-5 text-amber-950"><input className="mt-1 size-4 accent-emerald-700" type="checkbox" checked={withdrawalConfirmed} onChange={event => setWithdrawalConfirmed(event.target.checked)} /><span>I confirm that I want to transfer the entered amount to <strong>{data?.recipient?.bankName} · {data?.recipient?.accountNumberMasked}</strong>. This request cannot be cancelled after Paystack processes it.</span></label><div className="md:col-span-2"><button className="button button-primary" disabled={requestWithdrawal.isPending || withdrawalPin.length !== 4 || !withdrawalConfirmed}>{requestWithdrawal.isPending ? <><Loader2 className="animate-spin" size={16} /> Requesting transfer…</> : "Confirm bank withdrawal"}</button>{requestWithdrawal.error ? <p className="form-error mt-2">{requestWithdrawal.error.message}</p> : null}</div></form> : null}
      {data?.withdrawals.length ? <div className="mt-5 border-t border-slate-100 pt-4"><h3 className="text-sm font-extrabold text-slate-800">Recent withdrawal requests</h3><div className="mt-2 space-y-2">{data.withdrawals.slice(0, 3).map(request => <div className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm" key={request.id}><span className="font-semibold text-slate-700">{formatNaira(request.amount)}</span><span className="text-slate-500">{withdrawalLabels[request.status]}</span></div>)}</div></div> : null}
    </section>
    <section className="wallet-ledger"><div><span className="eyebrow">Transaction ledger</span><h2 className="section-title">Money in and out.</h2></div>{wallet.isLoading ? <p className="loading-line">Loading transactions…</p> : data?.transactions.length ? <div className="wallet-ledger-list">{data.transactions.map(entry => <div className="wallet-ledger-row" key={entry.id}><div><strong>{labels[entry.type]}</strong><span>{entry.description} · {entry.status}</span></div><strong className={entry.direction === "in" ? "wallet-money-in" : "wallet-money-out"}>{entry.direction === "in" ? "+" : "−"}{formatNaira(entry.amount)}</strong></div>)}</div> : <div className="empty-panel"><h3>No wallet activity yet.</h3><p>Once Paystack verifies a funding payment or you complete a wallet order, your activity will appear here.</p></div>}</section>
  </div></MarketplaceShell>;
}
